on: [push]

jobs:
  my-job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Hello world action step
        id: hello
        uses: Laren2121/Hello-barssom@0.0.2
        with:
          name: 'brown'
      # Use the output from the `hello` step
      - name: Get the output
        run: echo "The time was ${{ steps.hello.outputs.greeting }}"
